### PR TITLE
Enable support for enterprise GitHub + private repos

### LINKED ISSUE #2: Support private repos
Haven't looked into what this would entail

### PR DESCRIPTION
**Pull request by hipstersmoothie**
- allow any site with github in the name (ex: github.YOUR_COMPANY.com)
- use git clone to get repo so private repos + enterprise works

closes #2

After reading this comment https://github.com/Rich-Harris/degit/issues/2#issuecomment-319155100 I thought it might just work better to use `git clone` instead of trying to fetch the `.tar.gz`. Tested this on my enterprise GitHub and it seems to work.

I understand if you don't want to don't want to merge this, as it changes how it works a bit, but i think it's a bit more flexible. If you choose not to accept the change I'm fine with maintaining my own fork. I even already have a name ready to go: `regit` (I know the names taken but that would be a pretty fast dispute I think)

Thanks for the awesome library! I was going to implement the caching portion until i realized `degit` does it for me <3

EDIT: looks like i did #29 with less changes, his may be faster though since it will still use the .tar method. The code here is far simpler though and doesn't complicate the API at all

### CODE REVIEW

**Comment by peabnuts123** [comment]
As I understand, the entire point of this package is to pull the code from a repository without using `git clone` – as this is extremely time consuming for large repos (try cloning [gatsby](https://github.com/gatsbyjs/gatsby) or something).

**Comment by hipstersmoothie** [comment]
Yeah I’m probably just gonna go the maintain a fork route. The current
method of downloading the last release (or hypo something) doesn’t work on
enterprise github where everything requires login

**Comment by peabnuts123** [comment]
If you're just going to use `git clone` under the hood why not just use that instead?

**Comment by hipstersmoothie** [comment]
The caching degit does in pretty nice

**Comment by Rich-Harris** [comment]
As of 2.5.0 you can use `--mode=git` to clone with `git` (over SSH) instead of downloading a tarball. Thanks

**Pull request closed without merging**
